import oracledb
import csv

# CRIANDO A CONEXAO COM BANCO
try:
    conn = oracledb.connect(user='rm558823',
                            password='230605',
                            dsn='oracle.fiap.com.br:1521/orcl')
except Exception as e:
    print('Erro:', e)
    conexao, continua = False, False
else:
    conexao, continua = True, True

def listar_tabelas(conn):
    cursor = conn.cursor()
    cursor.execute("SELECT table_name FROM user_tables")
    tabelas = cursor.fetchall()
    print("Tabelas disponíveis no banco de dados:")
    for i, tabela in enumerate(tabelas):
        print(f"{i + 1}. {tabela[0]}")
    return [tabela[0] for tabela in tabelas]

def escolher_tabela(tabelas):
    while True:
        try:
            escolha = int(input("Escolha o número da tabela que deseja interagir: "))
            if 1 <= escolha <= len(tabelas):
                return tabelas[escolha - 1]
            else:
                print("Escolha inválida. Tente novamente.")
        except ValueError:
            print("Por favor, insira um número válido.")

def criar_tabela(conn):
    cursor = conn.cursor()
    comando = """
    CREATE TABLE T_ESTUDANTE (
        cd_estudante NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR2(100),
        idade NUMBER,
        endereco VARCHAR2(255),
        curso VARCHAR2(100)
    )
    """
    try:
        cursor.execute(comando)
        conn.commit()
        print("Tabela T_ESTUDANTE criada com sucesso.")
    except Exception as e:
        print("Erro ao criar tabela:", e)

def carregar_dados_csv(conn, arquivo_csv):
    cursor = conn.cursor()
    try:
        with open(arquivo_csv, mode='r', encoding='utf-8') as file:
            leitor_csv = csv.reader(file, delimiter=';')
            next(leitor_csv)  # Pular o cabeçalho
            for linha in leitor_csv:
                # Limpar espaços e tabulações extras nas colunas
                linha = [col.strip() for col in linha]

                if len(linha) == 4:
                    nome, idade, endereco, curso = linha
                    comando = f"INSERT INTO T_ESTUDANTE (nome, idade, endereco, curso) VALUES ('{nome}', {idade}, '{endereco}', '{curso}')"
                    cursor.execute(comando)
                else:
                    print(f"Erro: Linha inválida {linha}")
        conn.commit()
        print("Dados carregados com sucesso.")
    except Exception as e:
        print("Erro ao carregar dados do CSV:", e)

def excluir_estudante(conn, cd_estudante):
    cursor = conn.cursor()
    try:
        comando = f"DELETE FROM T_ESTUDANTE WHERE cd_estudante = {cd_estudante}"
        cursor.execute(comando)
        conn.commit()
        print(f"Estudante com código {cd_estudante} excluído com sucesso.")
    except Exception as e:
        print(f"Erro ao excluir estudante: {e}")

if conexao:
    while continua:
        print("""
        1. Criação da tabela de estudantes (T_ESTUDANTE)
        2. Carga de dados a partir do CSV
        3. Exclusão de um estudante da tabela de estudantes a partir de sua chave (cd_estudante)
        4. Consulta da tabela  
        5. Listar tabelas
        6. Sair
        7. Excluir tabela T_ESTUDANTE
        """)
        try:
            escolha = int(input("Escolha uma opção: "))

            if escolha == 1:
                criar_tabela(conn)

            elif escolha == 2:
                arquivo_csv = input("Informe o caminho do arquivo CSV: ")
                carregar_dados_csv(conn, arquivo_csv)

            elif escolha == 3:
                cd_estudante = int(input("Informe o código do estudante a ser excluído: "))
                excluir_estudante(conn, cd_estudante)

            elif escolha == 4:
                c_consulta = conn.cursor()
                comando = 'SELECT * FROM T_ESTUDANTE'
                c_consulta.execute(comando)
                lEstudantes = c_consulta.fetchall()
                for estudante in lEstudantes:
                    print(estudante)

            elif escolha == 5:
                tabelas = listar_tabelas(conn)
                tabela_escolhida = escolher_tabela(tabelas)
                print(f"Você escolheu a tabela: {tabela_escolhida}")
                c_consulta = conn.cursor()
                comando = f"SELECT * FROM {tabela_escolhida} WHERE ROWNUM <= 5"
                c_consulta.execute(comando)
                registros = c_consulta.fetchall()
                print(registros)

            elif escolha == 6:
                conn.close()
                print("Conexão com o banco de dados encerrada.")
                continua = False

            elif escolha == 7:
                c_consulta = conn.cursor()
                comando = 'DROP TABLE T_ESTUDANTE'
                c_consulta.execute(comando)
                print('Tabela T_ESTUDANTE excluída com sucesso!')

            else:
                print("Opção inválida. Tente novamente.")
        except ValueError:
            print("Por favor, insira um número válido.")
